### ISSUE TITLE
Node18 lambda layer requires ES Modules?

### ISSUE THREAD

**Issue by anthonyc4** [newrelic/newrelic-lambda-layers#147] opened 2023-03-29 14:20 UTC
[NOTE]: We have decide to upgrade our lambdas from Node 16 to Node 18.  We have applied the proper Lamdba Layer for Node 18.  Once we do so, our lambdas no longer function due to an error.  If we run in Node 16 (with the appropriate lambda layer), everything functions normally.  All we did we tell our lambda to run in node 18 and apply the correct layer

## Description

We took an existing lambda functioning that is using Node 16 and the right lambda layer for node 16 and ported it to Node 18 and the right lambda layer for node 18.  No other code changed.  We received the error below.  Our js file is `getDeal.js` not `getDeal.mjs`We use a default export of our handler

For node 16, we had this setup with `NEW_RELIC_LAMBDA_HANDLER` environment variable set to `getDeal.default`
![image](https://user-images.githubusercontent.com/53476204/228565280-f328f01b-eb0c-4443-82f6-a373ecf8939f.png)

For node 18, we have the same `NEW_RELIC_LAMBDA_HANDLER` environment variable set to `getDeal.default` with
![image](https://user-images.githubusercontent.com/53476204/228568542-4901be36-ea07-4b1a-998d-3c2e9c63a743.png)

(See error below)

## Steps to Reproduce

- Create a lambda not using es modules with an handler of `yourlambda.js`
- Set the `NEW_RELIC_LAMBDA_HANDLER` variable to `yourlambda.default` since we use a default export for our handler
- set the other environment variables `NEW_RELIC_ACCOUNT_ID`, `NEW_RELIC_EXTENSION_SEND_FUNCTION_LOGS` and `NEW_RELIC_LAMBDA_EXTENSION_ENABLED` as you normally would (in our case, both flags are true)
- Set the Lambda runtime to Node 16 and set the layer to `arn:aws:lambda:us-east-1:451483290750:layer:NewRelicNodeJS16X:46`
- Once you prove the lambda works then do the following:
- change the runtime to Node 18
- change the layer to ``

## Expected Behaviour

Upgrading the runtime and then the corresponding NR Lambda Layer should allow the code to work

## Relevant Logs / Console output

```
2023-03-29T13:14:44.756Z	undefined	ERROR	Unhandled Promise Rejection 	{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/getDeal.mjs' imported from /opt/nodejs/node_modules/newrelic-lambda-wrapper/index.js",
    "reason": {
        "errorType": "Error",
        "errorMessage": "Cannot find module '/var/task/getDeal.mjs' imported from /opt/nodejs/node_modules/newrelic-lambda-wrapper/index.js",
        "code": "ERR_MODULE_NOT_FOUND",
        "stack": [
            "Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/getDeal.mjs' imported from /opt/nodejs/node_modules/newrelic-lambda-wrapper/index.js",
            "    at new NodeError (node:internal/errors:400:5)",
            "    at finalizeResolution (node:internal/modules/esm/resolve:331:11)",
            "    at moduleResolve (node:internal/modules/esm/resolve:994:10)",
            "    at moduleResolveWithNodePath (node:internal/modules/esm/resolve:938:12)",
            "    at defaultResolve (node:internal/modules/esm/resolve:1202:79)",
            "    at nextResolve (node:internal/modules/esm/loader:163:28)",
            "    at ESMLoader.resolve (node:internal/modules/esm/loader:842:30)",
            "    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)",
            "    at ESMLoader.import (node:internal/modules/esm/loader:525:22)",
            "    at importModuleDynamically (node:internal/modules/cjs/loader:1151:29)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/getDeal.mjs' imported from /opt/nodejs/node_modules/newrelic-lambda-wrapper/index.js",
        "    at process.<anonymous> (file:///var/runtime/index.mjs:1188:17)",
        "    at process.emit (node:events:513:28)",
        "    at process.wrappedEmit [as emit] (/opt/nodejs/node_modules/newrelic/lib/instrumentation/core/globals.js:54:23)",
        "    at emit (node:internal/process/promises:149:20)",
        "    at processPromiseRejections (node:internal/process/promises:283:27)",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)"
    ]
}
```

## Your Environment
Lambda Node 16 and 18
commonjs

**Comment by anthonyc4** [comment] 2023-03-29 14:25
I noticed that my problem is almost identical to https://github.com/newrelic/newrelic-lambda-layers/issues/138

**Comment by mrickard** [comment] 2023-03-29 14:27
Closing as duplicate of #138

**Closed by mrickard** 2023-03-29 14:27 UTC
Labels: bug
