### ISSUE TITLE
"Cannot find module '/var/task/handler.mjs' imported from /opt/nodejs/node_modules/newrelic-lambda-wrapper/index.js"

### ISSUE THREAD

**Issue by okko** [newrelic/newrelic-lambda-layers#138] opened 2023-02-23 15:32 UTC
## Description

After updating runtime from Node16  to Node18, a handler that is processing SQS messages is failing.

## Steps to Reproduce

- Compile as commonjs.
- Use layer 'arn:aws:lambda:eu-west-1:451483290750:layer:NewRelicNodeJS18X:13' or :16.
- Run handler for SQS messages

## Expected Behaviour

Function runs without errors

## Relevant Logs / Console output

```
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/handler.mjs' imported from /opt/nodejs/node_modules/newrelic-lambda-wrapper/index.js",
    "reason": {
        "errorType": "Error",
        "errorMessage": "Cannot find module '/var/task/handler.mjs' imported from /opt/nodejs/node_modules/newrelic-lambda-wrapper/index.js",
        "code": "ERR_MODULE_NOT_FOUND",
        "stack": [
            "Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/handler.mjs' imported from /opt/nodejs/node_modules/newrelic-lambda-wrapper/index.js",
            "    at new NodeError (node:internal/errors:400:5)",
            "    at finalizeResolution (node:internal/modules/esm/resolve:331:11)",
            "    at moduleResolve (node:internal/modules/esm/resolve:994:10)",
            "    at moduleResolveWithNodePath (node:internal/modules/esm/resolve:938:12)",
            "    at defaultResolve (node:internal/modules/esm/resolve:1202:79)",
            "    at nextResolve (node:internal/modules/esm/loader:163:28)",
            "    at ESMLoader.resolve (node:internal/modules/esm/loader:842:30)",
            "    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)",
            "    at ESMLoader.import (node:internal/modules/esm/loader:525:22)",
            "    at importModuleDynamically (node:internal/modules/cjs/loader:1151:29)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/handler.mjs' imported from /opt/nodejs/node_modules/newrelic-lambda-wrapper/index.js",
        "    at process.<anonymous> (file:///var/runtime/index.mjs:1188:17)",
        "    at process.emit (node:events:513:28)",
        "    at process.wrappedEmit [as emit] (/opt/nodejs/node_modules/newrelic/lib/instrumentation/core/globals.js:54:23)",
        "    at emit (node:internal/process/promises:149:20)",
        "    at processPromiseRejections (node:internal/process/promises:283:27)",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)"
    ]
}
```
## Your Environment

Lambda
Node 18
commonjs (not ESM)
"aws-sdk": "2.1321.0"

## Additional context

HTTP API handlers work as expected.

**Comment by anthonyc4** [comment] 2023-03-29 14:27
I am as well I did not recognize this was the same when I posted https://github.com/newrelic/newrelic-lambda-layers/issues/147 until after I posted it

**Comment by mrickard** [comment] 2023-03-29 14:32
@anthonyc4 @okko Thank you for the report. Take a look at [our notes on ESM](https://github.com/newrelic/newrelic-lambda-layers#support-for-es-modules-nodejs)--recent versions of the layer changed the wrapper to be able to handle .mjs or .js handlers for Node 18 The Node 18 runtime patches `NODE_PATH` (via AWS-SDK v3), so our dynamic patching should work, but Node 14 and Node 16 runtimes still use AWS-SDK v2, which does not patch it. (`NODE_PATH` is not used in importing ESM in Node.)

One other factor that's caused people difficulty in updating from Node 16 to Node 18 is that the AWS-SDK v3 has a different API from v2. You'll see this in errors that are expressed under 18 but not 16, particularly with AWS services like SQS or SNS. If your function code's referencing AWS-SDK, you'll need to change how they're imported. See [the AWS-SDK docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/index.html) for the important differences.

**Comment by JanStevens** [comment] 2023-04-06 11:31
I'm using node v16 and I have the same issue. It only happend on a new deployed lambda, all old lambda's are working fine but the new one gives the same issue.

Seems like a regression, I would expect newrelic layers to stay compatible with node v16 without making any changes

**Comment by mrickard** [comment] 2023-04-06 14:20
@JanStevens Thank you for the report! 

Is this a Node 16 function that hasn't been updated to Node 18? In testing so far, this error emerges as a side effect of a function that's erroring. Would you be able to get us a repro case? 

For the moment, I'd recommend staying with the slightly older layer while we investigate.

**Comment by JanStevens** [comment] 2023-04-06 14:26
@mrickard I noticed we were on layer 47 but on an older `serverless-newrelic-lambda-layers` version (v3.4.0 vs v3.4.3). Bumping it to the latest version fixed it for us

**Comment by stellar-scottreed** [comment] 2023-04-14 19:19
I am having the same problem with lambda layer 47 on node 16.
Cannot find module '/var/task/index.mjs' imported from /opt/nodejs/node_modules/newrelic-lambda-wrapper/index.js"
NEW_RELIC_LAMBDA_HANDLER is "index.handler" and index.js exists.
Our index.js looks like this:
`exports.handler = async function (event) {`

I tried several versions prior to 47 and they all give the same error. It appears node 16 layer does not work at all.

**Comment by stellar-scottreed** [comment] 2023-04-28 15:23
Any update on this issue? The New Relic Lambda layer is unusable.

**Comment by mrickard** [comment] 2023-04-28 16:46
@stellar-scottreed Would you be able to open a ticket with support? Or supply a repro case? We've been unable to reproduce this condition with Node 16.

**Comment by spovlot** [comment] 2023-06-20 01:41
I am also having this problem with Node 16 using v53 of the NodeJS NR Lambda Layer.  I am having this issue after added an external dependency to the project.  I added "json-mask" using `npm install json-mask` and then added `const mask = require('json-mask');` to my js file without additional code.  If I remove the package from the code, the lambda runs without any problem.

**Comment by mrickard** [comment] 2023-06-20 15:02
@spovlot Thank you for the report. Currently we're refactoring the Node wrapper to handle CJS and ESM differently, but also provide clearer messaging around any problems. In this case, you were encountering an exception on loading your handler file, but the current wrapper presented it as the handler file not being found. 

Messaging should be improved with the new wrapper, which will be released in the next week or two.

**Comment by ddbhagat** [comment] 2023-06-21 10:17
Any updates here?
I am getting the same error if I `forceExclude` some of the `@aws-sdk` packages under serverless>webpack. I guess these @aws-sdk packages already available with nodejs 18.x !!

**Comment by tlrwagner** [comment] 2023-07-25 15:41
Having this issue as well. Would appreciate an update since this is preventing us from monitoring.

**Comment by ddbhagat** [comment] 2023-07-27 08:07
In my case,
I had updated the node version to 18 BUT the **serverless runtime(runtime in serverless.yml) was still 16**. And thus this issue showed up. After everything set to 18 the issue is gone.

**Comment by mrickard** [comment] 2023-10-10 19:07
Closing--this issue results from deploying ESM functions to runtimes earlier than Node 18.

**Closed by mrickard** 2023-10-10 19:07 UTC
Labels: bug
